apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: grafana-server
  name: grafana-server
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: grafana-server
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
